### ISSUE TITLE
App crashed when using MalaysiaMyKadFrontRecognizer / MalaysiaMyPrFrontRecognizer

### ISSUE THREAD

**Issue by kaisontan** [BlinkID/blinkid-react-native#101]
Hi. I have implemented blinkid-react-native plugin in my Android project. The plugin is working fine. However, in some android tablet, app crashed when scanning. The camera able to start live preview, however after awhile, the camera stop/hang on the live preview. My app crashed and restarted afterward. 

Using android studio logcat, I capture the following error: 
**Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffffc in tid 31416 (Recognition) [ 01-22 17:44:12.770 240: 240 W/ ] debuggerd: handling request: pid=30859 uid=10618 gid=10618 tid=31416**

I have googled the error message, it look like is a Segmentation/ Memory Leak Error in NDK.

**Comment by i1E** [comment]
Hi @kaisontan, 

can you please share the full logcat output? On which device(s) this crash happens and which version of the plugin you are using? 

Can you please check whether you will get the same crash on [this sample application](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID_AllRecognizersSample)?

**Comment by kaisontan** [comment]
Hi  @i1E , thanks for your assistance. I am using v4.5.0. My tablet is Samsung Galaxy Tab A, Android version 7.1.1, Memory 2GB.  I did't get the same crash on the sample application. 
[blink-react-native-fullLogcat-bug.txt](https://github.com/BlinkID/blinkid-react-native/files/2786234/blink-react-native-fullLogcat-bug.txt)

**Comment by kaisontan** [comment]
HI @i1E. 

The RN sample application builded with initReactNativeDemoApp.sh is working on the problematic device. 

I don't think is third party library problem as other devices is working fine with version 4.5.0. But I did notice that in version 4.5.0, the scanner has become harder to scan document. Compared to 4.4.0, version 4.5.0 required longer time to scan document.

**Comment by kaisontan** [comment]
Could it be Tablet Memory Issue? It look like v4.5.0 is using more RAM

v4.4.0
<img width="666" alt="blinkid-4 4 0" src="https://user-images.githubusercontent.com/41769691/51665679-4ebe7a80-1ff7-11e9-986a-27b689a21d7e.PNG">

v4.5.0
<img width="669" alt="blinkid-4 5 0" src="https://user-images.githubusercontent.com/41769691/51665704-59790f80-1ff7-11e9-8261-bed1d12f6c7f.PNG">

**Comment by kaisontan** [comment]
HI @i1E , 

Noted the problem. I think I will try optimised the memory usage of my App or try to revert back to v4.4.0. 

Thanks for your help.
