### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by raghavendramogeraya** [BlinkID/blinkid-react-native#103]
When I scan a Emirates ID, with date of birth '01/07/1908', it converts date into 01/07/2008, Since MRZ uses only 2 digit year format. Please let us know how MicroBlink converts 2 digit year into 4 digit year format?

**Comment by i1E** [comment]
Hi @raghavendramogeraya,

for the date of birth, we return most recent year that is in the past.

**Comment by raghavendramogeraya** [comment]
OK. Thanks. How it will converted for future dates? (For example: date of expiry) If we scan '1920', will it return 2020?

**Comment by i1E** [comment]
If it is not required for date to be in past, then for years < 69 we add 2000, and for years >=69 we add 1900 to convert to full year.

**Comment by mparadina** [comment]
Hi @raghavendramogeraya 

As this issue is inactive, I will close it.
If this is still an open issue for you, feel free to re-open this issue or create a new one.

Also, you can always contact us at support@microblink.com

Regards,
Milan
