### ISSUE TITLE
Removing Overlay. MBDocumentOverlaySettings

### ISSUE THREAD

**Issue by ajboxjr** [BlinkID/blinkid-react-native#106]
Is there a way to remove OverlayBorder (the white guiding section). While talking to tech support I was told vertical ID's are not supported, so I would like to remove the overlay altogether.

**Comment by jcular** [comment]
Our overlays come as is, you can try using different overlay, for example barcode overlay that adapts to the document being scanned might be a better choice here. You can't change the overlay unless you change the native implementations on android and ios.  Or you can make your custom overlay, again this would require that you write native implementations for custom overlay.

Kind regards,
Jure
