### ISSUE TITLE
Italian ID problem

### ISSUE THREAD

**Issue by IronTony** [BlinkID/blinkid-react-native#107]
Hi, I am trying to scan an Italian ID, but it seems to me that the it doesn't work. I have tried with the old and with the new Italian ID document.

This is the scan code I am using:

```
scan = async() => {
    console.log('scan');
    try {
      console.log('try');
      var itaRecognizer = new BlinkIDReactNative.ItalyDlFrontRecognizer();
      itaRecognizer.returnFaceImage = true;
      itaRecognizer.returnFullDocumentImage = true;
      var SuccessFrameGrabber = new BlinkIDReactNative.SuccessFrameGrabberRecognizer(itaRecognizer);

      const scanningResults = await BlinkIDReactNative.BlinkID.scanWithCamera(
        new BlinkIDReactNative.DocumentVerificationOverlaySettings(),
        new BlinkIDReactNative.RecognizerCollection([SuccessFrameGrabber]),
        licenseKey
      );

      console.log('scanningResults: ', scanningResults);   // <<<< doesn't do anything
    } catch (error) {
      console.log('Error: ', error);
      this.setState({ showImageDocument: false, resultImageDocument: '', showImageFace: false, resultImageFace: '', results: 'Scanning has been cancelled', showSuccessFrame: false,
        successFrame: ''});
    }
  }
```

What I can see on my Xcode debugger output is this message: _Skipping processing of this group, determined glare as more than 10%_

New ID: https://3.bp.blogspot.com/-ElN8FDDrPj4/WN0U6IkK7ZI/AAAAAAABjAI/92iG5fIxZ5EEYrvjKUOHm4_HldggOjUSQCLcB/s320/IMG_3189.jpg
Old ID: https://www.progettoomnia.it/storage/images/2017/06/26/5951157a742d7.jpg

**Comment by jcular** [comment]
Hi @IronTony,

`ItalyDlFrontRecognizer` is recognizer for Italian drivers licences, not identity cards.  You can use MRTDCombinedRecognzier to scan the front and the back side of new id cards, old id's are not supported.

Kind regards,
Jure

**Comment by IronTony** [comment]
@jcular super awesome, my fault.
Everything is working FANTASTIC!
Thx
