### ISSUE TITLE
Any chance BlinkInputRecognizer might make its way into this package?

### ISSUE THREAD

**Issue by brentron9000** [BlinkID/blinkid-react-native#109]
Just curious. Very impressed with the product so far! Thank you.

**Comment by dCubelic** [comment]
Hi @brentron9000,

we are currently working on creating react-native wrappers for our BlinkInput product (https://github.com/BlinkInput), which includes BlinkInputRecognizer. Hopefully that will meet your needs.

We will let you know when it is finished.

Best regards,
Dominik
