### ISSUE TITLE
[IOS] MicroblinkModule.xcodeproj is not updated

### ISSUE THREAD

**Issue by faezmurshidi** [BlinkID/blinkid-react-native#114]
<img width="1020" alt="Screenshot 2019-05-09 at 12 03 40 PM" src="https://user-images.githubusercontent.com/9053513/57426654-b15c1f00-7252-11e9-8ff4-47752fd5149f.png">

Missing MBPassportRecognizerWrapper in Recognizers/wrapper

<img width="1079" alt="Screenshot 2019-05-09 at 9 22 58 AM" src="https://user-images.githubusercontent.com/9053513/57426706-da7caf80-7252-11e9-82e2-9f2df20463cc.png">

BlinkID Version 4.9.0

**Comment by richeterre** [comment]
I'm seeing the same issue – building the demo project fails with the error shown above.

**Comment by culoi** [comment]
This issue is now fixed in the version 4.9.1
