### ISSUE TITLE
Returning both document image and face image

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#12]
Hello,

Is it possible to return both the scanned document image and the corresponding face image in one scan?
In the RN module, it doesn't seem to be possible right now, but will it be in the future? (ie. does the Android and iOS SDKs provide this feature?)

This issue is the same as https://github.com/BlinkID/blinkid-react-native-ios/issues/8, I lost track of this one.

**Comment by juraskrlec** [comment]
@Minishlink We will check and will return to you with answer

**Comment by mvayngrib** [comment]
@juraskrlec any update on this? Thanks!

**Comment by i1E** [comment]
This is possible, starting with v2.0.0 of the plugin, but please use the latest version (at the moment it is v4.5.0) because we have significantly changed the API in v4.0.0 and simplified usage of the plugin.
