### ISSUE TITLE
Taking too much time to read the Malaysian MyCard

### ISSUE THREAD

**Issue by rahulcs1989** [BlinkID/blinkid-react-native#123]
For my project I am using BlinkIDReactNative.MalaysiaMyKadFrontRecognizer(). It takes too much time to scan the card. Anyone faced the same problem before? Any help appreciated.

**Comment by peterWilson34** [comment]
I had the same problem using `UnitedArabEmiratesIdFrontRecognizerResult`.

**Comment by culoi** [comment]
Hi all,

We will need more information on this topic. 

- Which devices are you using? 
- A version of the SDK?
- Are you scanning a real document or the sample from the internet?
- Is the document scanning from the computer screen? 
- What is the background and lighting conditions? 
- Did you compare your project vs our demo app from the App/Play Store? 

There are so many factors that can impact the scan speed.

If you are able, I suggest that you contact us directly at support@microblink.com with more information so we can check this out.

Regards

**Comment by rahulcs1989** [comment]
@peterWilson34 @culoi I downgraded to 4.4 and we have more IDs like MyKad, MyKas, Passport, I-Kad etc. And if we are including all readers in a single scan, it will go to each ID module and check so that it will take long time. So I added a popup where the user can select which ID he is going to scan.
