### ISSUE TITLE
Cannot scan US license with the reac-native demo app

### ISSUE THREAD

**Issue by basilin** [BlinkID/blinkid-react-native#125]
I try building the react-native demo app, i was able to successfully build and run the app as you guys suggested but wasn't able to scan license with it. Am running it on Android 9 Oreo

**Comment by culoi** [comment]
Hi @basilin,

Did you scan the front or the back side of the document? In our sample app, we are expecting the back side, where the PDF417 barcode is. 

For the front, you have to  use BlinkIDRecognizer which scans the front side of the USDL. https://github.com/BlinkID/blinkid-android#-blinkid-recognizer

List of supported states is available [here](https://github.com/BlinkID/blinkid-android/blob/master/documentation/BlinkIDRecognizer.md).

Quick question, before we try to troubleshoot it further. Are you able to scan the DL with our BlinkID Demo app from the Play Store: https://play.google.com/store/apps/details?id=com.microblink.blinkidapp&hl=en_US

You can also contact us to support@microblink.com with more details. 

Regards

**Comment by basilin** [comment]
Yes, it worked, thanks!
