### ISSUE TITLE
Error in `pod install`

### ISSUE THREAD

**Issue by peterWilson34** [BlinkID/blinkid-react-native#130]
After I run `npm i blinkid-react-native` then `react-native link blinkid-react-native` 
as per the instructions I run `pod install` and I always get this error 

> [!] Invalid `Podfile` file: [!] No podspec exists at path `./blinkid-react-native.podspec`..

Notes 

1. I always get this error even when I remove `pod 'PPBlinkID', '~> 4.11.0'` from the pod file.
2. the error only disappears if I did `npm uninstall blinkid-react-native` or if I remove `use_native_modules`
3. I am using react-native 0.60 and blinkid-react-native 4.11

**Comment by davidperrenoud** [comment]
@juraskrlec @i1E Any news? This bug was not happening with v4.9.1.

**Comment by juraskrlec** [comment]
[v5.0.0](https://github.com/BlinkID/blinkid-react-native/releases/tag/v5.0.0) has been released with added support for latest react-native version.
