### ISSUE TITLE
BlinkID v5.0.0 issue with UAE National ID

### ISSUE THREAD

**Issue by DaniShalash** [BlinkID/blinkid-react-native#133]
### Description:
With the new v5.0.0 SDK, there's a couple of recognizers that auto detect the document type and extract its data. However, when upgraded and tested on UAE national ID, we're getting invalid data (check the following image):
![Image 10-27-19 at 11 32 AM](https://user-images.githubusercontent.com/19424170/67631306-db130c00-f8ad-11e9-8e83-596c99efdd23.jpg)

We're not getting any errors or any indicator for a misconfiguration though.

Also, it would be nice to allow the developer to specify the document type that the recognizer should look for, because currently with this upgrade, a user can basically scan his Australian ID successfully only to tell them from our side that it's the wrong document and only UAE ID allowed (obviously, but you got the point :) ).

### Environemt:
_OS: ios 12
xCode: 10.2.1
React-Native: 0.60.5
Blink ID: 5.0.0_

**Comment by Brankacro** [comment]
Hello @DaniShalash 

We hope that you tried our v5.3.0 and that your issue is resolved.
If not, please let us know. For any questions you may have, we stand at your disposal. Also, feel free to contact us directly at support@microblink.com

Looking forward to hearing from you.
Best regards,

Branka
