### ISSUE TITLE
blinkid-react-native handling expired license 

### ISSUE THREAD

**Issue by noor94Test** [BlinkID/blinkid-react-native#134]
blinkid-react-native handling expired license I tired it with try and catch but it doesn't work?
any help?
` try {
      var mrtdRecognizer = await new BlinkIDReactNative.MrtdRecognizer();
      mrtdRecognizer.returnFullDocumentImage = true;

      var mrtdSuccessFrameGrabber = await new BlinkIDReactNative.SuccessFrameGrabberRecognizer(
        mrtdRecognizer
      );

      const scanningResults = await BlinkIDReactNative.BlinkID.scanWithCamera(
        new BlinkIDReactNative.DocumentOverlaySettings(),
        new BlinkIDReactNative.RecognizerCollection([mrtdSuccessFrameGrabber]),
        licenseKey
      );
}catch(error){
console.log(error)
}
`
Result => The app is always crash when the license is expired

**Comment by IvaKeresa** [comment]
Hi noor94Test, 

We did use NSError in versions 2.x and 3.x, and we had much more issues back then than that we have now. 
The most common case was that the developers simply didn’t put effort to handle the invalid license key issue in the proper way.
However, I agree that just the way NSExceptions are implemented in ObjC makes the new approach also not ideal. We’ll definitely rethink this once again. We need to take into account the users using ObjC and Swift as well. 

I hope this was helpful to you. 

Best regards, 

Iva

**Comment by noor94Test** [comment]
Hi @IvaKeresa  is there any workaround to handle it?

**Comment by IvaKeresa** [comment]
Hi noor94Test,

The only way to stop this from happening is to use a production license key. 
With the demo license, unfortunately, nothing can be done.

Best regards, 

Iva

**Comment by Brankacro** [comment]
Hi noor94Test,

I am closing this issue. In case you have any additional questions, feel free to contact us.
Kind regards.

Branka
