### ISSUE TITLE
Unable to detect closing blinkid modal by swiping down on IOS 13

### ISSUE THREAD

**Issue by ahmadallo1** [BlinkID/blinkid-react-native#135]
I'm using blinkid-react-native we are unable to detect when the blinkid modal is dismissed by swiping down on IOS 13.

this issue is only on IOS 13 since is older versions we are unable to dismiss modal by swiping down.

is there's any solution for this issue any help?

"react-native": "0.61.3",
"blinkid-react-native": "^4.11.2"

**Comment by Brankacro** [comment]
Hello,
Can you please tell us on which device is this happening? And if you could please explain a bit more in detail what do you mean by "swiping down"?
Any additional info would be helpful.
Many thanks.

Best regards,
Branka

**Comment by ahmadallo1** [comment]
Hello @Brankacro 
I using blinkid react native I have tested it on all IOS devices it working properly and we can dismiss the scan modal with the button x check the following screenshot

![Screen Shot 2019-12-09 at 1 20 05 PM](https://user-images.githubusercontent.com/56399010/70432036-f82f2300-1a86-11ea-81a3-79f6ebf14fbd.png)


but in IOS 13 we are able to dismiss this scan modal also by swiping down check the following screenshot

![Screen Shot 2019-12-09 at 1 20 05 PM](https://user-images.githubusercontent.com/56399010/70432208-6378f500-1a87-11ea-87a0-b53fba41007c.png)

we are not able to detect the modal dismiss when swiping down

thanks,
Ahmad

**Comment by Brankacro** [comment]
Hello Ahmad,
thank you for the details. 
iOS 13 is the default modal sheet. With the iOS 13, you can always dismiss the VC swiping down. There are two options, but you will need to change it in iOS cod if you want to forbid it, or if you want to be able to dismiss it on swipe.

1. if you want to forbid it, then you need to put the option
**isModalInPresentation=YES** , inside our code, in native wrapper by react native, where we present VC

2. if you want to figure out when it is swiping down and act regarding it, then you will need in native, in our wrapper set this protocol https://developer.apple.com/documentation/uikit/uiadaptivepresentationcontrollerdelegate
and program what you want to be the next action.

Hope this was helpful. For any additional questions, feel free to contact us.
You can always contact us directly at support@microblink.com

Best regards.
Branka

**Comment by ahmadallo1** [comment]
@Brankacro the issue that the scan modal is autogenerated we are not building it.
BlinkIDReactNative.BlinkID.scanWithCamera is displaying the scan modal

**Comment by Brankacro** [comment]
Hello @ahmadallo1 
you need to go to our native wrapper and add the options on your own. Please, open the Blinkid wrapper natively in Xcode and add the options that you require.
Hope this helps.
Regards,
Branka

**Comment by Brankacro** [comment]
Hello @ahmadallo1 
We are closing this issue as it is inactive. In case of any additional questions, please let us know.
Also, you can always contact us directly at support@microblink.com We will be glad to assist you.
Best regards,
Branka

**Comment by joerupen** [comment]
I had exactly the same issue today with `react-native 0.68.0`, `blinkid 5.14.0` and` react 17`. I was testing the `PassportRecognizer`.
Essentially this line was never returning

`await BlinkIDNative.scanWithCamera(overlaySettings, recognizerCollection, licenseObject);`

The swipe as well as the close button did not work at all.

The problem in my case was that I was using `overlaySettings` which were not compatible with the `PassportRecognizer`.

an example that doesn't work (and shows the blocking UI).

```
const passportRecognizer = new BlinkIDReactNative.PassportRecognizer();
const recognizerCollection = new BlinkIDReactNative.RecognizerCollection([passportRecognizer])
// also DocumentVerificationOverlaySettings does not work
const overlaySettings = new BlinkIDReactNative.BlinkIdOverlaySettings()
await BlinkIDNative.scanWithCamera(overlaySettings, recognizerCollection, licenseObject);
```

an example that worked for me:
```
const passportRecognizer = new BlinkIDReactNative.PassportRecognizer();
const recognizerCollection = new BlinkIDReactNative.RecognizerCollection([passportRecognizer])
const overlaySettings = new BlinkIDReactNative.DocumentOverlaySettings()
await BlinkIDNative.scanWithCamera(overlaySettings, recognizerCollection, licenseObject);
```

It's not clear from the documentation, which overlays are compatible with which recognizers, I guess many of us started off with the code from the tutorial. In older versions of blinkId this was not a problem.

**Comment by MBrizic01** [comment]
Hello @joerupen 
Thank you for reaching out.

To get the most out of our product, I recommend you use the BlinkIdRecognizer (or BlinkIDCombined Recognizer) as we deprecated the Passport Recognizer in 2020 (you can read about it [here](https://github.com/BlinkID/blinkid-ios/blob/v5.8.0/Release%20notes.md#deprecated-recognizers)).

I would also suggest you try our MBBlinkIdOverlayViewController, which is optimally designed to be used with MBBlinkIdRecognizer and MBBlinkIdCombinedRecognizer. 
You can see an example in our sample app [here](https://github.com/BlinkID/blinkid-react-native/blob/master/sample_files/index.js#L79-L87).

I believe that combining these two methods would solve your problem and give you the optimized experience of our product.

Please test this and let me know if it helped.
