### ISSUE TITLE
Android known issue - update Readme

### ISSUE THREAD

**Issue by idomaz00** [BlinkID/blinkid-react-native#138]
Hi,

I recently upgraded react-native version to `0.61.5` and then updated blinkid package to 
`5.1.0`. While building for android, I had issue with **ReactSwipeRefreshLayout** you mentioned in Readme. I followed your instructions regarding addition to `build.gradle` but it still did not work.

Only after adding both implementation it worked ([from react-navigation issue thread](https://github.com/react-navigation/react-navigation/issues/6267)):
```sh
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```
I am not sure if my project is somehow different and therefore had to include both implementations (I am not using react-native-screens, but I do use react-navigation) but I figured it did not hurt to post here if somebody else runs into this issue. 
In case this is not related to combined usage of blinkid and react-navigation (or other), then your readme file should be updated. I am happy to provide PR for this if you need one.

Regards

**Comment by Brankacro** [comment]
Hello @idomaz00,
In the readme file, we added an explanation for the fix for our sample. What you mentioned is specific for your project. We really appreciate your feedback, it may help other users. 
In case of any additional questions, you can always contact us directly at support@microblink.com, we will gladly assist you.
Best regards,
Branka

**Comment by Brankacro** [comment]
Hello @idomaz00 
We would like to solve this issue. In case of any questions or feedback, feel free to contact us.
As mentioned earlier, you can also contact us directly at support@microblink.com
We would be more than glad to help.
Best regards,
Branka
