### ISSUE TITLE
How to scan the ID card in other language, not english?

### ISSUE THREAD

**Issue by lightning331** [BlinkID/blinkid-react-native#140]
I tested the demo example. It works well with the document with English.
Is there any way to scan the card with another language? For example, what about the ID card in Spanish?

**Comment by juraskrlec** [comment]
Hi @lightning331 

you can see [here](https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizer.md) every document that we currently support with BlinkIdRecognizer.

**Comment by lightning331** [comment]
Hi @juraskrlec 

I have attached an example image here.
The app is showing the following message:
  "Document not recognized"
  "scan the front side of a supported document."

It is the same even though I use other cards. 
I am not sure what's wrong with that.

![358d7da3-9180-46bb-8916-a9a9582fb9e1_16-9-aspect-ratio_default_0](https://user-images.githubusercontent.com/40198243/74044036-618ace00-4a05-11ea-9fdc-62e4e2b214c5.jpg)

**Comment by Brankacro** [comment]
Hi @lightning331 

Thank you for attaching the sample.
Jura sent you earlier the link where you can see supported identity documents. 
From the provided link https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizer.md you can see that at the moment we do not support documents from Panama. As we are constantly improving our technologies, we hope that in the future we will support documents from Panama as well.
In case of any additional questions, please let us know. You can always contact us directly at support@microblink.com.
Regards,
Branka

**Comment by lightning331** [comment]
Ok, got it.
Thanks for your support.

Regards,
Jack

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Brankacro** [comment]
Hi Jack,
Thank you. If we can help you with anything else, please let us know.
Best regards,
Branka
