### ISSUE TITLE
pod install seem stucked

### ISSUE THREAD

**Issue by jacky-ew** [BlinkID/blinkid-react-native#144]
<img width="299" alt="Screenshot 2020-04-07 at 16 50 04" src="https://user-images.githubusercontent.com/56298610/78649355-e738d600-78ef-11ea-8427-21984737cdbf.png">

no respond after running pod install

**Comment by mparadina** [comment]
Hi @jacky-ew 

What version of Pods are you currently running?
Also, do you get any kind of exception afterward or it just stays on the "install" part?

Regards,
Milan

**Comment by jacky-ew** [comment]
closing this. it was my connection being too slow.
