### ISSUE TITLE
Scanning passport (MY) but not working

### ISSUE THREAD

**Issue by jacky-ew** [BlinkID/blinkid-react-native#145]
i tried to scan Malaysia Passport but no result is returned. 
1. Do i need to flip to scan back of documents? cause it still can proceed quickly without me changing the scan view
2. Sometimes alert documents no recognised.
3. same for driver license and working permit in malaysia

im using BlinkID license key. The description: 

> The product fully powered by our machine learning technology. Mobile SDK enables scanning and intelligent data extraction from ID cards, passports, driver’s licenses, travel visas, work permits, as well as from all documents containing MRZ or PDF417 barcode.

**Comment by Cerovec** [comment]
Hi @jacky-ew,

Thank you for your question.

Can you tell us which recognizer are you using and how you set up the scanning process? Ideally, we would get the code that you use to set up your recognizers and your UI.

Thanks,
Jurica.

**Comment by jacky-ew** [comment]
```
var blinkIdInstance = new BlinkIDReactNative.BlinkIdCombinedRecognizer();
blinkIdInstance.returnFullDocumentImage = true;
blinkIdInstance.returnFaceImage = true;
```

Hi here is the initialization of the library in code

**Comment by Cerovec** [comment]
Hi @jacky-ew,

For passports, you need to use PassportRecognizer, not the BlinkIdCombinedRecognizer.

BlinkIdCombinedRecognizer will work for you MyKads, MyTenteras, etc. (the complete list is [here](https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizer.md).

However, for passports, you need a different recognizer.

We hope this helps!
Jurica.
