### ISSUE TITLE
The Info.plist file is missing the required key

### ISSUE THREAD

**Issue by OnurVar** [BlinkID/blinkid-react-native#174]
# The problem

Hello. Latest version(5.10.0) is failing to upload the archive to AppStore connect. It might be related with [this issue on blinkid-capacitor](https://github.com/BlinkID/blinkid-capacitor/issues/13). I haven't found a way to apply the suggested workaround in our app.

> ERROR ITMS-90057: "The bundle 'Payload/App-Dev.app/Frameworks/Microblink.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
ERROR ITMS-90056: "This bundle Payload/App-Dev.app/Frameworks/Microblink.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
Return status of iTunes Transporter was 1: ERROR ITMS-90057: "The bundle 'Payload/App-Dev.app/Frameworks/Microblink.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please fin\nERROR ITMS-90056: "This bundle Payload/App-Dev.app/Frameworks/Microblink.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 5.10.0                |
| ReactNative Version     | 0.64.0                |
| Occurs on Android             |  no                |
| Occurs on iOS     | yes                |

**Comment by mparadina** [comment]
Hi @OnurVar 

Yes, this issue could be connected to the mentioned GitHub issue.

In your React-Native project, you can find the framework in your Pods folder, by going to the PPBlinkID folder. 
There you will see the `Microblink.xcframework` and when you enter it, you will see the `Info.plist` file.

In that file, add:
```
<key>CFBundleVersion</key>
<string>1</string>
```

When you add the key, you will also see three folders:
```
ios-arm64_armv7
ios-arm64_i386_x86_64-simulator
ios-arm64_x86_64-maccatalyst
```

Every folder contains the Microblink.framework, which you will need to enter and find the `Info.plist` file.
Once you find and enter it, add:
```
<key>CFBundleShortVersionString</key>
<string>5.10.0</string>
<key>CFBundleVersion</key>
<string>1</string>
```

Did you already do this workaround?

Milan

**Comment by OnurVar** [comment]
Hi @mparadina,

Seems like adding these values to info.plist fixed this issue for now. Thanks for the help.

Best regards

**Comment by stringparser** [comment]
Is this fixed on the Pod with the last version?

**Comment by mparadina** [comment]
Hi @stringparser 

Yes, the issue regarding `Info.plist` should now be fixed with version 5.11.0.

Please try it and let me know if it is working as expected.

Regards,
Milan

**Comment by stringparser** [comment]
> Hi @stringparser
> 
> Yes, the issue regarding `Info.plist` should now be fixed with version 5.11.0.
> 
> Please try it and let me know if it is working as expected.
> 
> Regards,
> Milan

Sweet thank you. I'll try it out.

**Comment by stringparser** [comment]
@mparadina yes it did work thank you 🚀

**Comment by mparadina** [comment]
@stringparser that's great news! Glad to hear that it works! :)

**Comment by stringparser** [comment]
> @stringparser that's great news! Glad to hear that it works! :)

yes to make sure I did 

```
cd ios
pod deintegrate 
pod install
``` 

since first I tried the solution here :) (which works but forget about continuous deployment then... or write some script for it :D)

Anyway thanks! :)
