### ISSUE TITLE
New "Real Oklahoma ID" isn't supported by Blink ID 

### ISSUE THREAD

**Issue by kevinswartz** [BlinkID/blinkid-react-native#179]
Hi Guys,
We've had some reports from our customers that the new "Real Oklahoma ID" isn't scanning properly with Blink ID.  I don't have a picture, but here's a link about it: https://oklahoma.gov/dps/real-id/get-real-id.html

We're currently on blinkid-react-native v5.11.0.
Thanks for your help!

**Comment by anjapenic** [comment]
Hello @kevinswartz,

We're not supporting the new Real Oklahoma ID yet, but we will forward your request internally. Could you share with us, does that document have a MRZ or a PDF417 barcode on the back side? Maybe you could extract the data from there and skip OCR until we add support for the document.

Best regards,
Anja

**Comment by kevinswartz** [comment]
Thanks for the response Anja!

I don't have an example handy.  I googled around a bit and from what I can tell it has a standard US Drivers License MRZ on the back, but I don't have anything good enough to test code against.

My code uses the BlinkIdCombinedRecognizer as in the screenshot attached.  Does it appear to you that this should pull MRZ data if detected?  That's my intention here.
Thanks again!

<img width="773" alt="Screen Shot 2021-08-09 at 8 56 30 AM" src="https://user-images.githubusercontent.com/5995089/128736800-50f4d7f5-3923-41bb-9a13-a21612430ad8.png">

**Comment by anjapenic** [comment]
Hi @kevinswartz,

Could you contact us at support@microblink.com so we could inspect your license key and see if it allows you to read the MRZ?

Thanks!

Best regards,
Anja

**Comment by kevinswartz** [comment]
Hi Anja,
I sent something this morning.  Let me know if you need anything else.
Thanks,
Kevin

**Comment by anjapenic** [comment]
Hi @kevinswartz,

Closing this issue since we've solved it via e-mail. If you need any further assistance, feel free to reach out at support@microblink.com.

Best regards,
Anja
