### ISSUE TITLE
 can't read s/com.sample/com.microblink.sample/g: No such file or directory

### ISSUE THREAD

**Issue by imdadulhaque1** [BlinkID/blinkid-react-native#185]
After cloning the git using `git clone https://github.com/BlinkID/blinkid-react-native.git` .  Due to the [VIDEO](https://vimeo.com/289850200) in **BlinkID/blinkid-react-native** [Description](https://github.com/BlinkID/blinkid-react-native) , I have run `./initReactNativeSampleApp.sh` and then I faced an error as ` can't read s/com.sample/com.microblink.sample/g: No such file or directory` . For this reason, I think I faced an error which I have explained [issue no-184 for licensee key error](https://github.com/BlinkID/blinkid-react-native/issues/184) . Please show me the right direction so that I can solve this issue and please don't encourage me further to contact via **microblink.com** help section because of the sending more times but I have gotten a response properly.  The issue is also given attached file, please concern there.

![com sample](https://user-images.githubusercontent.com/45633928/134870951-778a81f1-45d3-4626-83f4-70a5c6e19f74.png)

**Comment by anjapenic** [comment]
Hello @imdadulhaque1,

Closing this issue since we've got in contact via e-mail. Please feel free to reopen it if you need further assistance.

Best regards,
Anja
