### ISSUE TITLE
How to replace Microblink text and logo from Scanning page in blinkid-react-native

### ISSUE THREAD

**Issue by imdadulhaque1** [BlinkID/blinkid-react-native#186]
From the attached file there have been shown **MICROBLINK** logo and the text **Powered by MICROBLINK** but I want to change these . So how should I change it ? 
**Advanced Thanks**!
![Screenshot_29](https://user-images.githubusercontent.com/45633928/135219607-3bb12bca-76a4-4c21-bb84-600456857359.png)

**Comment by mparadina** [comment]
Hi @imdadulhaque1 

The Microblink watermark and logo are part of our trial license key.
Once you acquire the production license key, the watermarks are removed and no longer displayed on the scanning UI.

Hope this helped.

Regards,
Milan

**Comment by imdadulhaque1** [comment]
@mparadina Thanks for the information!
