### ISSUE TITLE
Support for localisation in react-native wrapper?

### ISSUE THREAD

**Issue by msegers** [BlinkID/blinkid-react-native#187]
Hi, maybe somewhat of a question, but how is the support for overriding the localisation in BlinkID using react native?
We noticed the german translations are pretty formal, and our app communicates in a very informal matter, ideally we'd like to override a few strings.

If I'm not mistaken this currently would require us to edit some files which are currently auto generated?

https://github.com/BlinkID/blinkid-android#-translation-and-localization

**Comment by msegers** [comment]
Actually it seems like you allow overrides outside the module, I'll see if I can get something working

**Comment by anjapenic** [comment]
Hi @msegers,

Apologies for a late reply! Have you tried setting the strings here - [https://github.com/BlinkID/blinkid-react-native/blob/master/BlinkID/overlays/blinkidOverlays.js](https://github.com/BlinkID/blinkid-react-native/blob/master/BlinkID/overlays/blinkidOverlays.js)? If so, please let us know if it helped.

Best regards,
Anja

**Comment by msegers** [comment]
Thanks! will try that! Didn't see it in the readme! We noticed our language overrides wasn't working on our production app (it works fine in our staging/development apps which have the same logic). Worst case scenario we can override all strings this way, will try soon!

**Comment by msegers** [comment]
@anjapenic I was wondering though, looking at the code, if I'm already using some other overlaySettings, I cannot add this as well?
I was using `new BlinkIDReactNative.DocumentVerificationOverlaySettings();` and it doesn't appear possible to have multiple overlaysettings objects?

**Comment by msegers** [comment]
It works absolutely fine, thanks!
