### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by aarango** [BlinkID/blinkid-react-native#193]
I'm trying to compile the library in my project and I can't. What should I fix? please help

I need run android in sdk 30

`* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.appcompat:appcompat:1.4.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\a07d9a43843b87a815a1ba9bba735402\transformed\appcompat-1.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.appcompat:appcompat-resources:1.4.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\fb13af5f6f81beee8d19d96782b4a069\transformed\jetified-appcompat-resources-1.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.emoji2:emoji2-views-helper:1.0.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\d4cddcaf6e32293dca466443b146c652\transformed\jetified-emoji2-views-helper-1.0.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.emoji2:emoji2:1.0.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\38729e149656c0c85c7f2acce0c9dafa\transformed\jetified-emoji2-1.0.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\d9763394d7a2747fce682fa75f371244\transformed\core-1.7.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-process:2.4.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\2c63e08ad52ed05d2de70ae87b56f471\transformed\jetified-lifecycle-process-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-runtime:2.4.0.
        AAR metadata file: C:\Users\afbermudez\.gradle\caches\transforms-3\96a6fc2a6feb38f2bb5bdc9211883217\transformed\lifecycle-runtime-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 31s
94 actionable tasks: 90 executed, 4 up-to-date`

Android
**`buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"

    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../android"))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(["node", "--print", "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), "../dist"))
        }

        google()
        mavenCentral()
        jcenter()
        maven { url "http://maven.microblink.com" }
        maven { url 'https://www.jitpack.io' }`**

![Captura](https://user-images.githubusercontent.com/5192867/149860634-272c96ed-b1f0-4c9e-bd67-2075b67bda79.PNG)

**Comment by mparadina** [comment]
Hi @aarango 

Can you please tell me if you can reproduce the mentioned behaviour on our sample application as well, or just when you try to add the SDK into your project?

Also to ask, is there a specific reason why the SDK versions need to be set as '30'?
Lastly, are you using the latest version of the SDK (5.15.1)?

**Comment by Titozzz** [comment]
FYI : I had the same issue, but went digging some more.

React native as of now if using SDK 30 and JDK 8. When using SDK 31, you'll probably need JDK 11 to have a successful build.
Also there is an issue between appcompat 1.4 and <TextInput>, see https://github.com/facebook/react-native/commit/e21f8ec34984551f87a306672160cc88e67e4793 and it won't be fixed until 0.68.X

TDLR pick one:

- Downgrade this lib to a version not using app compat 1.4

- Update SDK to 31, JDK to 11 and patch-package until https://github.com/facebook/react-native/commit/e21f8ec34984551f87a306672160cc88e67e4793 is released.

**Comment by aarango** [comment]
thanks I solved this issue
