### ISSUE TITLE
Invalid date after scanning a MyKad on ios

### ISSUE THREAD

**Issue by Nhacsam** [BlinkID/blinkid-react-native#20]
Hi, 
We are experimenting some trouble scanning a MyKad card on ios. Every time we scan a card, the birthdate we get is 1 day before the one on the card.

I think this is a timezone issue.

When my birthdate is 1958-08-21

If my phone timezone is the Paris one, I get in `ownerBirthdate` : `1958-08-20 23:00:00 +0000`
If my timezone is in Malaysia : `1958-08-20 16:30:00 +0000`

Thanks,

**Comment by cularj** [comment]
Hi @Nhacsam 

We fixed this issue in the new release, v1.3.1.
Now date of birth format on ios is the same as the one on android, YYMMDD.

Kind regards, 
Jure

**Comment by Nhacsam** [comment]
@cularj Thanks, it works
