### ISSUE TITLE
Android app build fail: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by dragorwyin** [BlinkID/blinkid-react-native#200]
Hello, I have a following error:

* What went wrong:
Execution failed for task ':blinkid-react-native:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\a833098\.gradle\caches\transforms-3\8e1cfd4e749775f195798be2005dc765\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

I'm using:
```
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
```

and tried also 

```
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.core:core:1.6.0'

configurations.all {
    resolutionStrategy {
        force 'androidx.core:core:1.6.0'
        force 'androidx.core:core-ktx:1.6.0'
    }
}
```

in app/build.gradle

but nothing help me out. Can you provide any solution?

**Comment by dragorwyin** [comment]
I need to use sdkVersion 31 because of another screen splash package.

**Comment by anjapenic** [comment]
Hi @dragorwyin, could you please share with us the steps you took when implementing the plugin?

**Comment by dragorwyin** [comment]
Hi, sorry, didn't see the request before. I solved that problem, but I had done a lot of experiments and it's working now. I'm not able to explain what I did.
