### ISSUE TITLE
Beep sound

### ISSUE THREAD

**Issue by nazarTrynko** [BlinkID/blinkid-react-native#22]
Hi! Is there a way to disable beep sound?

**Comment by lirfu** [comment]
Hi @nazarTrynko,

by default beep is disabled on iOS and enabled on Android and cannot be changed from JS.

This will be fixed in the next minor release by adding a property that enables/disables the beep.
We will notify you when the release is out.

**Comment by nazarTrynko** [comment]
Hi @lirfu! Nice to hear that, thank you!

**Comment by lirfu** [comment]
Hi @nazarTrynko,

the new release [v1.3.2](https://github.com/BlinkID/blinkid-react-native/releases/tag/v1.3.2) adds control over the beep sound.

**Comment by nazarTrynko** [comment]
Awesome! Thank you @lirfu!
