### ISSUE TITLE
Unable to scan IMM13P if country code is not MYS (PHL, JPY, etc)

### ISSUE THREAD

**Issue by chai-cd** [BlinkID/blinkid-react-native#220]
Hi, I am trying to scan IMM13P but facing some issue. I can scan it if the country code is MYS and not able to scan using other country code such as PHL, JPN, etc. I have tried the Microblink in Play Store, the app also behave the same.

BlinkId Version: 6.7.0

Below is my code:
```
import * as BlinkIDReactNative from 'blinkid-react-native';

const blinkidRecognizer = new BlinkIDReactNative.BlinkIdSingleSideRecognizer();
blinkidRecognizer.returnFullDocumentImage = true;
blinkidRecognizer.fullDocumentImageDpi = 400;
blinkidRecognizer.validateResultCharacters = false;

const blinkIdOverlaySettings =
  new BlinkIDReactNative.BlinkIdOverlaySettings();
blinkIdOverlaySettings.enableBeep = true;
blinkIdOverlaySettings.overlaySettingsType = 'DocumentOverlaySettings';

const scanningResults = await BlinkIDReactNative.BlinkID.scanWithCamera(
  blinkIdOverlaySettings,
  new BlinkIDReactNative.RecognizerCollection([blinkidRecognizer]),
  licenseKey
);
```

Below is the test data:

1. Using MYS IMM13P (Ok)
![image](https://github.com/user-attachments/assets/8e4b64ed-c5ab-4da9-b1a1-e5489e3e2000)

2. Using PHL IMM13P (Failed)
![image](https://github.com/user-attachments/assets/be7829fb-bd85-4aea-b276-48a922e3f698)

**Comment by MBrizic01** [comment]
Hi @chai-cd, this is because this type of document, which we classify as My Pass IMM13P, must have MYS as an issuing country for the MRZ parsing logic we implement to work correctly. This is a Malaysian document, so it can't be issued by the Philipines or Japan, and our recognizer consequently can't read it

**Comment by chai-cd** [comment]
@MBrizic01 Got it, thanks
