### ISSUE TITLE
Integrate lastest changes from blinkdid-react-native-ios

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#3]
Hi, it seems that the latest changes from the deprecated `blinkdid-react-native-ios` were not merged into this repository. Could you fix this please?

**Comment by juraskrlec** [comment]
Hi @Minishlink 

it will be added, we'll let you know when new release is ready.

Best,
Jura

**Comment by Minishlink** [comment]
Thanks @juraskrlec 
FYI, I tested my branch (#4) on both Android and iOS and it works well. ;)
