### ISSUE TITLE
Error while trying to run android 

### ISSUE THREAD

**Issue by OrLevy23** [BlinkID/blinkid-react-native#31]
While trying to run android i'm getting the following error:
> Could not expand ZIP '/Users/user/Projects/project/node_modules/blinkid-react-native/src/android/build/intermediates/exploded-aar/com.microblink/blinkid/3.12.0/jars/classes.jar'.

**Comment by culoi** [comment]
Hello @OrLevy23

Can you please try to clean and build project again?

Please let me know if it works for you.

Regards,

Ivan

**Comment by OrLevy23** [comment]
Found out how to solve the issue anyway, need to update gradle version to 3.0.1, not sure what is the issue but the project just don't compile with the generic react-native init project that i've wanted to test your library, you might want to document it or something
