### ISSUE TITLE
Disable toast with "Time based license"

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#33]
Hello,

Can we remove the toast message "Time-based license"? The user doesn't care about this...

**Comment by juraskrlec** [comment]
Hi @Minishlink 

this toast message is shown for developers to make them aware when they are building production version to put production key, not developer key. This toast message will be hidden when you put production license key.

Best,
Jura

**Comment by Minishlink** [comment]
Thanks for the info @juraskrlec!
