### ISSUE TITLE
BlinkID SDK update 3.14

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#35]
Hello,

Are you planning on upgrading the SDK to the latest version? If so, would you mind estimating a release time?

Thanks! :)

**Comment by lirfu** [comment]
Hi @Minishlink,

the next release will be out by the end of next week. In this release both SDKs will be upgraded to most recent versions.

**Comment by lirfu** [comment]
Hi @Minishlink,

the android SDK is updated to v3.14 in the [latest release](https://github.com/BlinkID/blinkid-react-native/releases/tag/v1.4.1).

**Comment by Minishlink** [comment]
Thanks @lirfu!
