### ISSUE TITLE
BlinkID.scan returns nothing in Expo detached app

### ISSUE THREAD

**Issue by LoongerBuxus** [BlinkID/blinkid-react-native#39]
Hi, I'm trying to implement your example code in my Expo detached app for Android platform.

Everything looks ok, when I click the botton to scan a passport the camera appears, it recognizes the document and the mrz, the beep sounds and the app returns to the original view, but no error or data comes out.

If I try to log the scanningResult returned from the scan method it never appears in the console. 
Any suggestion?

Thanks in advance.

**Comment by culoi** [comment]
Hello @LoongerBuxus 

Are you able to share code sample of your app or part of the code on how did you implement the return of the result?

Regards

**Comment by LoongerBuxus** [comment]
Hi @culoi,

I'm following the usage code you show in the readme:

`const scanningResult = await BlinkID.scan(...)`

But scanningResult never gets a value.

**Comment by LoongerBuxus** [comment]
I think this library is not compatible with Expo detached apps, so I eventually moved my app to a react-native init one and it worked smoothly.

**Comment by naartjie** [comment]
> Expo detached apps

@LoongerBuxus you mean ejected Expo apps? see here, it should be working in `1.4.2` now (see [https://github.com/BlinkID/blinkid-react-native/issues/34#issuecomment-359165397](this comment)).

**Comment by LoongerBuxus** [comment]
@naartjie yes, in Expo terminology eject=detach.. but I can see that issue is in iOS platform, and mine is in Android, as startActivityForResult is not being called with any result from ScanIntent.

**Comment by naartjie** [comment]
@LoongerBuxus Ah sorry, my bad. That issue is not related at all.

> I have tried to make my own native module and the patern startActivitForResult->onActivityResult is not working with detached Expo apps.

Hmm... This does sound strange, is it not something specific to your setup, rather than detached apps specifically - it seems like it would be a pretty major issue if it was the case.

**Comment by LoongerBuxus** [comment]
@naartjie I know other people is having the same problem, maybe there is a workaround for making native modules work in detached Expo apps in Android but I opted to recreate my app with rn init as I only had the Expo Camera dependency.
