### ISSUE TITLE
Updates 1.4.1 and 1.4.2 broke Malaysian MyKad support

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#40]
Scanning a Malaysian MyKad card with the following code now only returns a `resultImageCropped` and nothing else.

```js
const scanningResult = await BlinkID.scan(Platform.select(config.BLINKID_LICENSE_KEY), {
    useFrontCamera: false,
    shouldReturnCroppedImage: true,
    shouldReturnSuccessfulImage: false,
    recognizers: [BlinkID.RECOGNIZER_MRTD, BlinkID.RECOGNIZER_MYKAD],
});
```

**Comment by culoi** [comment]
Hello @Minishlink 

Thank you for the report, I just tested with both version and also with the latest one (1.4.4.) and I can confirm that results are not returned. 

I'm raising an issue to our dev team. I will notify you once we fix this issue. 

Once again, thank you for the reporting this.

Regards

**Comment by Minishlink** [comment]
Thanks @culoi :)

**Comment by culoi** [comment]
Hello Minishlink,

Can you please contact us at support@microblink.com

Regards

**Comment by Minishlink** [comment]
Hello @culoi,

Do you have any updates on this?

Thanks

**Comment by culoi** [comment]
Hi @Minishlink 

Couple days ago, we updated React Native repo. It now supports v0.55.0

If you didn't, please star and watch our repo to get instant updates of new releases.

Are you able to test with the latest version and check if this issue still happens? 

With this version we are able to successfully scan front side of the MyKad.

Best!

**Comment by Minishlink** [comment]
@culoi It works again 👍
