### ISSUE TITLE
Source code for Android: customising UI

### ISSUE THREAD

**Issue by naartjie** [BlinkID/blinkid-react-native#41]
Hi, I am trying to customise the UI overlay (on Android), as per the [FAQ](https://github.com/BlinkID/blinkid-react-native#faq).

I've gone quite far down the rabbit hole of creating a custom `RecognizerView`, but there are quite a lot of things which I would like to reuse from this RN wrapper, and the sources for these files (from the BlinkID Android SDK) would come in handy, in order to create my own custom `ScanCard` activity:

`ScanCard.java`
`ScanActivity.java`
`BaseScanActivity.java`

Are sources for these available anywhere, or are these strictly proprietary?

**Comment by i1E** [comment]
Hi @naartjie,

sources for these activities are not publicly available. You can use source code from the [BlinkID sample applications](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample). Especially useful sample application is [BlinkIDSampleCustomUI](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDSampleCustomUI). You can use that source code as starting point for building your custom scan activity.

**Comment by i1E** [comment]
Hi @naartjie,

actually, result extraction and passing to React-Native JS is done inside of the [BlinkIDModule](https://github.com/BlinkID/blinkid-react-native/blob/master/src/android/src/main/java/com/microblink/reactnative/blinkid/BlinkIDModule.java) and it is completely separated from the activity which is used for scanning. You don't need to reimplement that part, just return the scanning results from your scan activity to BlinkIDModule by using intent extras, as it is done when using provided ScanCard activity. 

If you are using recognizer from the BlinkID native SDK which is not supported in the current version of the react-native plugin, you will have to implement result mapping to JS for that specific recognizer in BlinkIDModule.java and you can see how it is done for currently supported recognizers.
