### ISSUE TITLE
semi-consistent ocr errors EUDL

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-react-native#43]
hey guys :)

i just upgraded from ~2.9.0 to ~2.15.0 in my Podfile and i'm hitting more OCR issues it seems.

i'm scanning this image:

![image](https://user-images.githubusercontent.com/83948/38683185-ddba6cfc-3e3a-11e8-8639-27fced6207e4.png)

and consistently getting results like this:

![image](https://user-images.githubusercontent.com/83948/38683163-d2fb5830-3e3a-11e8-9d31-81d9e55852e0.png)

see the extra letters on the first and last name

**Comment by DoDoENT** [comment]
Hi @mvayngrib, this behavior is expected. Note the rotated text "TEST SAMPLE" on the right side. Rotated "E" OCR is recognized as "LJ" and rotated "L" as "-I". Try scanning real IDs.

**Comment by mvayngrib** [comment]
@DoDoENT ah ic, ok thanks!
