### ISSUE TITLE
Scanning Code39 (South African ID Book)

### ISSUE THREAD

**Issue by unicornRainbows** [BlinkID/blinkid-react-native#47]
Hello,

I am trying to figure out how to get results from a Code39 barcode found on some IDbooks.

I see the key in blinkid-react-native/keys/usdl_keys.js but unable to detect and pass back the results.

We are also using our own PPCameraOverlayViewController

Any ideas? <3

**Comment by i1E** [comment]
Hi @unicornRainbows,

I suppose that you are using USDLRecognizer. It does not support Code39 barcode extraction. If you want to scan Code39 barcode, you can implement your custom support for it. For example, on Android, you can use [BarcodeRecognizer](https://github.com/BlinkID/blinkid-android#barcodeRecognizer) and add support for scanning barcodes in the [Android plugin implementation](https://github.com/BlinkID/blinkid-react-native/blob/master/src/android/src/main/java/com/microblink/reactnative/blinkid/BlinkIDModule.java).

**Comment by unicornRainbows** [comment]
Thanks for the reply,

Could you indicate how I would add this in for iOS? We got android sorted already!

Awesome STUFF!

**Comment by cularj** [comment]
Hi @unicornRainbows,

You can do the same on iOS, you can also use [BarcodeRecognizer](https://github.com/BlinkID/blinkid-ios/wiki/Using-Barcode-recognizer) and add it to the [iOS plugin implementation](https://github.com/BlinkID/blinkid-react-native/blob/master/src/ios/BlinkIDReactNative/BlinkIDReactNative/BlinkIDReactNative.mm).

Kind regards,
Jure
