### ISSUE TITLE
`MicroBlink/MicroBlink.h` file not found, cannot launch the demo

### ISSUE THREAD

**Issue by marcusegues** [BlinkID/blinkid-react-native#48]
I cannot successfully launch the demo.

I am using 
- macOS Sierra 10.12.6
- node v8.9.1
- npm 5.8.0

Steps to reproduce:
- `git clone https://github.com/BlinkID/blinkid-react-native.git`
-  `cd blinkid-react-native/`
- `./initReactNativeDemoApp.sh`
- `cd BlinkIDReactNative/`
- Here I try to open `BlinkIDReactNative.xcworkspace` as in the video tutorial, but it does not exist. Instead:
- `cd ios`
- Now open `BlinkIDReactNative.xcodeproj` with `XCode`
- I delete the `tvOS` targets, and change the code signing fields as required.
- Go to `Info.plist` and add the Privacy - Camera Usage Description key
- Click `Run`

Result
- The build fails:
![image](https://user-images.githubusercontent.com/14809309/38921832-fb46bd0a-42f6-11e8-9cde-d84f8a512f96.png)

Why is this?

**Comment by cularj** [comment]
Hi @marcusegues,

Do you have [Cocoapods](https://guides.cocoapods.org/using/getting-started.html) installed? The script for initialising demo app automatically creates a podfile and downloads the iOS SDK using it. Since you are missing `MicroBlink.h` I think this might be the issue.

Kind regards,
Jure

**Comment by marcusegues** [comment]
Hi @cularj, here is what I did, based on the `README` in this repo and the installation instructions for `cocoapods`:
- `brew install git-lfs`
- `git lfs install`
- `sudo gem install cocoapods`
- `pod install`
- Then, in `XCode` I run again, and get another build error, a different one:
![image](https://user-images.githubusercontent.com/14809309/38924338-fe9a7ae0-42fc-11e8-979e-7725c1faa7e7.png)

PS I do not know my way around XCode at all!

**Comment by marcusegues** [comment]
Here's what I did to get the build to succeed, after having installed `cocoapads` as above:
- Started over again by deleting the directory `BlinkIDReactNative/` created by the `./initReactNativeDemoApp.sh` command
- Run `./initReactNativeDemoApp.sh`
- cd `BlinkIDReactNative/ios`
- Now I can see `BlinkIDReactNative.xcworkspace` and I open that with `XCode`
- Go through the steps of code signing and setting the privacy - camera in the `Info.plist`
- Run

Now the build succeeds, but I get a red screen error on my device: `Cannot find entry file index.ios.js in any of the roots: ...`

**Comment by nomi9995** [comment]
@marcusegues  i manually linked blinkid-react-native to my project. i have checked framework search path is correct. but this error is comming continously. but it is running will in demo (./initReactNativeDemoApp.sh)
