### ISSUE TITLE
License key error when attempting to scan

### ISSUE THREAD

**Issue by marcusegues** [BlinkID/blinkid-react-native#50]
Got the demo to run on my iPhone device, but when I click on `Scan`, the camera opens but I get an alert as below:

![image](https://user-images.githubusercontent.com/14809309/38927594-93292a0e-4306-11e8-93f0-ee93e7bffef4.png)

Why is this? I cannot scan anything.

**Comment by marcusegues** [comment]
I have the license key from registration, but how do I add it to the app?

**Comment by marcusegues** [comment]
I generated a license for `BlinkID` on `iOS`. Not sure what to do with it though.

**Comment by marcusegues** [comment]
Okay so here is the solution:
Generate a license for `iOS`:
![image](https://user-images.githubusercontent.com/14809309/38929737-a4dba9c8-430d-11e8-877e-4bad840f5a33.png)

Go in the repo and change code by adding the license to `index.ios.js`:
![image](https://user-images.githubusercontent.com/14809309/38929780-c5bf6dbe-430d-11e8-82c1-7081e310fd36.png)

**Comment by Tichuottt** [comment]
It doesn't work for me, I've done all the steps and it still throw me that error

**Comment by culoi** [comment]
Hello,

Please make sure that you generate license key for the correct SDK that you are using. If you are using BlinkID SDK, you have to generat key for BlinkID. Keys for BlinkInput or PDF417 wont work with BlinkID SDK.

Regards
