### ISSUE TITLE
Is there any way of using BlinkID with expo(CRNA)?

### ISSUE THREAD

**Issue by sardarwaseemjaved** [BlinkID/blinkid-react-native#56]
I am new to react-native and i want everything to be simple so I am using expo (CRNA).
But I can't seem to find a way to use BlinkID with expo project.
I started new CRNA project and installed blinkid-react-native package and then copied the code from of blinkID for card scanning
I start the app with npm start the app runs successfully but when I tap scan button it returns the following error:
Undefined is not an object(evaluating 'blinkidReactNative.BlinkID.scan')
As far as I understand it has something to do with the following step "react-native link blinkid-react-native" and "the step with Maven" because It is not supported in the CRNA projects.

Now I don't want to eject from expo and I also want to use BlinkID, is there any possibility of using BlinkID with CRNA project?

**Comment by mparadina** [comment]
Hi @sardarwaseemjaved 

As this issue is inactive, I am closing it.
However, if this is still an open issue for you, feel free to re-open this one or create a new issue.

Also, you can always contact us directly at support@microblink.com for any additional questions.

Regards,
Milan
