### ISSUE TITLE
Unable to detect UK/US Drivers License

### ISSUE THREAD

**Issue by zakgrant** [BlinkID/blinkid-react-native#6]
Hi,

I have integrated this into my react-native app. I can successfully detect MRTD documents, and documents with faces on them. However, when I attempt to do driver licenses from the EU and US nothing happens other than the scanning blue dots appearing with the frame for detecting document.

I have also checked to ensure that the MicroBlink.framework installed by cocoa-pods is approx 95mb in size for PPBlinkID 2.10.0

I am currently using a demo license, is this a limitation due to the license?

Any help would be greatly appreciated.

Thanks,

Zak.

**Comment by juraskrlec** [comment]
Hi, 

Have you tried scanning back of US Driver License?

Best regards,
Jura Skrlec

**Comment by zakgrant** [comment]
Hi @juraskrlec,

Ah ok it works with the rear of the US driver license 👍 

What about the UK license, is there anything I have to do specifically to have it identified?

Thanks,

Zak.

**Comment by juraskrlec** [comment]
Hi @zakgrant 

All European driver license are scanned with EUDL recognizer. 

Best,
Jura Skrlec
