### ISSUE TITLE
Alert.alert('message') breaks the scanning modal

### ISSUE THREAD

**Issue by mariorodriguespt** [BlinkID/blinkid-react-native#63]
I'm using the example app in the documentation and during my development process I add a statement like `Alert.alert('inside native');` to test if I was getting messages from a `WebView` via `window.postMessage`.

Spend some time figuring out why and once I remove the alert, everything works as expected.
The alert was placed inside: `async scan() {`

The package should be resilient to the React Native core API.

**Comment by cularj** [comment]
Hi @mariorodriguespt,

did you try debugging, what is the output of the logs?
I tried to add `Alert.alert('inside native');` in the `async scan()` and it works, did you import `Alert`?

Kind regards,
Jure

**Comment by mariorodriguespt** [comment]
@cularj I got no logs at all. The scanning modal wouldn't  just open at all. It was silent.

There are the versions I used:
```
"dependencies": {
    "blinkid-react-native": "^4.0.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-navigation": "^2.6.2"
  }
```

**Comment by jcular** [comment]
Hi @mariorodriguespt

as I stated before, did you import Alert? I tried to do the exact thing and everthing worked, could you send us our sample code with changes that can reproduce this issue.

Kind regards,
Jure

**Comment by mparadina** [comment]
Hello @mariorodriguespt 

We’re closing this issue as it is inactive, but please let us know if this is still an open issue for you.
Also, you can always contact us directly at support@microblink.com

Best,
Milan
