### ISSUE TITLE
initReactNativeDemoApp.sh - blank screen

### ISSUE THREAD

**Issue by devfubar** [BlinkID/blinkid-react-native#67]
After cloning the repo and running `./initReactNativeDemoApp.sh` everything seems fine. However, when I click on the "scan" button on the app I just get a blank screen with the blue "crosshairs". Doesn't seem to be any errors. It looks similar to #61 and it does feel like a permission thing as I don't get asked to give permission to use the camera. I also, as that issue suggested, changed my `android/app/src/main/AndroidManifest.xml` so that it looks like this;

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.blinkidreactnative">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by culoi** [comment]
Hello @devfubar 

> However, when I click on the "scan" button on the app I just get a blank screen with the blue "crosshairs". Doesn't seem to be any errors. It looks similar to #61 and it does feel like a permission thing as I don't get asked to give permission to use the camera.

This looks like the issue with the camera. Are you able to test with a real Android device and check if it works? Setting the camera on the emulator might be tricky and can often cause the issues like this.

Best regards

**Comment by jcular** [comment]
Closed due to inactivity.
