### ISSUE TITLE
XCode build error: Argument list too long: recursive header expansion failed at...

### ISSUE THREAD

**Issue by llanginger** [BlinkID/blinkid-react-native#7]
Hi there,

I'm fairly new to react native so I'm not sure precisely where the root of this error lies, but after following all the setup instructions xcode is throwing the following error when attempting the "run" the demo app:

`Argument list too long: recursive header expansion failed at <path to my project folder>BlinkIdTest/node_modules/blinkid-react-native/src/ios/BlinkIDReactNative/../../../../react-native/third-party/boost_1_63_0/boost/spirit/home/karma/detail.`

I have tried both adding blinkid-react-native to an existing project as well as a completely clean directory, deleting node_modules and reinstalling and even rebooting my machine - same result each time. 

Any help would be appreciated!

**Comment by llanginger** [comment]
Naming mistake! New issue has arisen but I will open that separately!

**Comment by thomashermine** [comment]
@llanginger Could you explain what naming error you had? I followed the setup instructions to integrate this lib into an existing app, and XCode build fail with the same recursive header error.

**Comment by nomi9995** [comment]
@llanginger how did you resolve this issue
