### ISSUE TITLE
How to hide message: "Using time-limited license"

### ISSUE THREAD

**Issue by SuTran** [BlinkID/blinkid-react-native#71]
Hi BlinkID Team,

We've just bought a license for using blinkid
I know there is a way to hide the message ""Using time-limited license" by reading your [Release/v3.12.0 Notes](https://github.com/BlinkID/blinkid-android/pull/59)
But I'm not clear on the way how to archive this. Where does `EXTRAS_SHOW_TIME_LIMITED_LICENSE_KEY_WARNING` coming from. Where to put those code in context of react-native etc
Thank for your support!

**Comment by i1E** [comment]
Hi @SuTran,

in the current version of the react-native wrapper for BlinkID SDK, there is no setting for disabling this warning through the JavaScript API. This option will be exposed to JavaScript in the next release.

For now, you can disable the warning on the Android by modifying the wrapper code. In the `MicroblinkModule`, after [this line of code](https://github.com/BlinkID/blinkid-react-native/blob/master/BlinkID/src/android/src/main/java/com/microblink/reactnative/MicroblinkModule.java#L81), just add the following line:

```
MicroblinkSDK.setShowTimeLimitedLicenseWarning(false);
```

**Comment by i1E** [comment]
Hi @SuTran,

in the latest version of the blinkid-react-native v4.2.0 it is possible to disable warning for the time limited license key through the JavaScrip API. Method scanWithCamera now accepts license object as third argument which can be used to disable warning. Just set its member `showTimeLimitedLicenseKeyWarning` to false. Please check the new [BlinkIDWrapper implementation](https://github.com/BlinkID/blinkid-react-native/blob/master/BlinkID/index.js).
