### ISSUE TITLE
MrtdCombinedRecognizer signResult NullPointerException

### ISSUE THREAD

**Issue by matias91** [BlinkID/blinkid-react-native#73]
Hi!

My app started to crash when i tried to use `MrtdCombinedRecognizer`.
I had to use `adb logcat` to track the issue, and found a `NullPointerException` starting from `MrtdCombinedRecognizerSerialization.java` at line 37.

Apparently the problem appears only if `signResult` isn't setted to **true**.

Just want to let you know. This might be helpful for someone else.
Thanks in advance for all the great work!

**Comment by i1E** [comment]
Hi @matias91,

which version of the plugin you are using? Please update to the latest version. This should be fixed in v4.2.0.
