### ISSUE TITLE
[iOS][TypeError: undefined is not an object (evaluating 'BlinkIDNative.scanWithCamera')]

### ISSUE THREAD

**Issue by iserifith** [BlinkID/blinkid-react-native#74]
Hello.

I've been having the same issue as #61 with pretty much the same code. 
Running with Expo and Console logging the `BlinkIDNative.scanWithCamera'`  returns `[TypeError: undefined is not an object (evaluating 'BlinkIDNative.scanWithCamera')]`

**Comment by jcular** [comment]
Hi @iserifith,

if I'm not mistaken you can't add native modules to Expo app, you need to eject it to use native modules.

Kind regards,
Jure
