### ISSUE TITLE
Support dynamic versions of React Native

### ISSUE THREAD

**Issue by janpieterz** [BlinkID/blinkid-react-native#75]
Not too familiar with building RN libraries, but would it be an idea to support dynamic versions of React Native instead of hard links?
This way, a new version comes out it doesn't require any work from your end. There's of course the danger that the library wouldn't work because of big changes.

We updated from 0.55 to 0.56 a while ago (I see it's supported now) and this was the only dependency that didn't work, seemingly because of this: https://github.com/BlinkID/blinkid-react-native/blob/master/BlinkID/src/android/build.gradle#L28

(Some) other dependencies seem to reference React Native as follows, something the react-native-create-library tool also sets:
```
compile 'com.facebook.react:react-native:+'
```

**Comment by i1E** [comment]
Hi @janpieterz,

thank you for the suggestion. We have been thinking about that, but as the react-native is not a stable platform, with every new version something is broken and we cannot use dynamic versions. When we are publishing a new version of BlinkID wrapper, we always test both platforms (Android and iOS) with the latest version of the RN and if everything works fine, or we are able to make things work, we also update the RN version.

You can always update the RN dependency in your project and try the latest version.

**Comment by janpieterz** [comment]
@i1E Thanks for getting back.
Ah, if each version needed fixes this makes sense so far. I think we tried to update but because the version was hard linked we couldn't test it out on the next version of RN. Not sure how far we tried to push this though.
