### ISSUE TITLE
Cannot read property 'scanWithCamera' of undefined

### ISSUE THREAD

**Issue by rvkuzmik** [BlinkID/blinkid-react-native#79]
```
TypeError: Cannot read property 'scanWithCamera' of undefined
    at BlinkIDWrapper.scanWithCamera$ (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:8251:63)
    at tryCatch (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29494:19)
    at Generator.invoke [as _invoke] (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29667:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29537:23)
    at tryCatch (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29494:19)
    at invoke (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29570:22)
    at blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:29598:13
    at tryCallTwo (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:10310:7)
    at doResolve (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:10474:15)
    at new Promise (blob:http://10.0.0.175:8081/35ee6e5e-959d-41ca-ae21-da3932a39909:10333:5)
```

This is in Index.js:67

I tried to implement this in my app and got this error so I went and got the demo app and installed it on my iPhone with xCode and I still get the same error. What could it be?

**Comment by rvkuzmik** [comment]
I was emailing back and forth with support and I was able to start the Demo App after linking it properly. But After taking the same steps on my app to implement, I still get this same error.

**Comment by ajboxjr** [comment]
Same here.

**Comment by rvkuzmik** [comment]
I ended up building my own ID scanning feature with React Native Camera. Never got BlinkID to work properly.

**Comment by ajboxjr** [comment]
is there an open repo? I really need it for my application

**Comment by rvkuzmik** [comment]
No open repo. I do have a cheat sheet for the barcode data. The barcode from a state ID is 'PDF417'.

> // BARCODE DATA CHEAT SHEET
DCB NONE                         // Virginia Specific Restrictions
DCD NONE                         // Virginia Specific Endorsements
DBA 00000000                     // License Expiration Date
DCS LAST                       // Last Name
DAC FIRST                        // First Name
DAD MIDDLE                      // Middle Name
DBD 00000000                     // License or ID Document Issue Date
DBB 00000000                     // Date Of Birth
DBC 1                            // Sex 1=Male 0=Female
DAY GRN                          // Eye Color
DAU 777 in                       // Height in Inches
DAG ADDRESS             // Address
DAI CITY                  // City
DAJ STATE                           // State
DAK 00000                    // Zip Code 
DAQ 000000000                 // License or ID Number
DCF 0000000000000000    // Document Discriminator
DCG USA                          // Country territory of issuance
DDE N                            // Family Name Truncation
DDF N                            // Family Names Truncation
DDG N                            // Middle Names Truncation
DCJ 000000000000                // Audit information
DDB 00000000000                     // Card Revision Date
DAW 777                          // Weight in LBS
DDH 0000000000                     // Under 18 Until
DDJ 0000000000                     // Under 21 Until

[Here](https://github.com/rvkuzmik/vatm/blob/master/src/screens/IDScanScreen/IDScan.js) is the validation and stuff I did. Note that this could be done way better, I slapped this together and never refactored.

**Comment by jcular** [comment]
Hi @ajboxjr,

can you tell me what version of react-native you're using and what version of blinkid-react-native are you trying to use?

Kind regards,
Jure

**Comment by ajboxjr** [comment]
I am using version 58.5 of react native and blink-id 4.7.0

**Comment by jcular** [comment]
Can you paste the output you get when you run initReactNativeDemo script?
Are there any errors when you try to add blinkid-react-native to your project?

**Comment by ajboxjr** [comment]
I got it to work! I changed the init script to the name of my project and moved my source files(index.js, images, js files .etc) and package.json to the BlinkIDReactNative folder. I would be really great to have the initReactNativeDemo script allow for custom pod file and workspace names. Would really help other developers prevent issues on installation. Just a suggestion

**Comment by mparadina** [comment]
Hello,

As this issue is inactive, I will close it. 
If this is still an open issue, please re-open it or create a new one.

Also, if you have any additional questions, feel free to contact us directly at support@microblink.com

Regards,
Milan

**Comment by TwinkleMali** [comment]
This is in Index.js:67

I tried to implement the code &got this error.

![Screenshot 2020-09-08 at 5 52 05 PM](https://user-images.githubusercontent.com/21214437/92476121-184d6780-f1fc-11ea-9991-7318a4606fa3.png)

**Comment by mparadina** [comment]
Hi @TwinkleMali 

Would you mind taking us through the steps on how did you implement the SDK?

Also, can you try to run our demo app without getting any exceptions?

Regards,
Milan

**Comment by AbijahKaj** [comment]
I had the same issue on iOS.
Solved it by adding this line to `Podfile`
```
pod 'blinkid-react-native', :path =>  '../node_modules/blinkid-react-native/blinkid-react-native.podspec'
```
