### ISSUE TITLE
How to scan the Spain National ID Card ?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-react-native#81]
Hi,

I Want to Scan the Spain National ID card. I find only the Spain DL Card. It's possible to Scan the Spain National Card front and back.

Thanks.

**Comment by culoi** [comment]
Hello @kiritnim 

You can use MRTDCombinedRecognizer for scanning the front and back side of the Spain DL as it. 
If you are using CombinedRecognizer there is also mandatory to use documentVerificationOverlay as it's best optimised for scanning the both sides of the document.

If you only need info from the ID, than you can use single MRTDRecgonizer and scan only back side of the ID.

Please find out our sample video, it was created for scanning the USDL, but principe is similar: https://github.com/BlinkID/blinkid-react-native#using-documentverificationoverlay-and-combinedrecognizer

Here you can find list of all available recognizers for our BlinkID ReactNative SDK: https://github.com/BlinkID/blinkid-react-native/tree/master/BlinkID/recognizers

Regards

**Comment by mparadina** [comment]
Hi @kiritm-nimblechapps 

I hope we resolved your issue.

I am closing this issue, but please let us know if you have any further difficulties.
Also, you can always contact us directly at support@microblink.com

Regards,
Milan
