### ISSUE TITLE
Can I do the customise view of Camera for Card Scanning.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-react-native#82]
Hi.

I want to some customisation of the camera view in React native. I used your library, Now I want to customise the Card scanning frame and it's border color, Text and Navigation Bar also cancel button. How can i do. I find the some string which "Position ID Card in the frame" can change .
 
![screen shot 2018-10-11 at 10 02 05 am](https://user-images.githubusercontent.com/17870723/46780987-06779700-cd3d-11e8-905f-6c7a87e964db.png)

**Comment by jcular** [comment]
Hi @kiritnim,

customising UI isn't possible without writing native code.
Check out this for [android](
https://github.com/BlinkID/blinkid-android#-changing-the-appearance-of-built-in-activities-and-scanning-overlays) and this for [ios](
https://github.com/BlinkID/blinkid-ios#-ui-customizations-of-built-in-mboverlayviewcontrollers-and-mboverlaysubviews).

Kind regards,
Jure

**Comment by mparadina** [comment]
Hi @kiritm-nimblechapps 

As this issue is inactive we would like to solve it.

In case of any questions, feel free to re-open the issue or create a new one.
Also, you can always contact us directly at support@microblink.com for further questions.

Regards,
Milan
