### ISSUE TITLE
BlinkID does not support React Native v0.57

### ISSUE THREAD

**Issue by kiyokokozui** [BlinkID/blinkid-react-native#84]
I upgraded my react native to 0.57 and the error log shows that blinkid requires react native 0.56 to run.

> Could not find com.facebook.react:react-native:0.56.0.
  Searched in the following locations:
      https://jcenter.bintray.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://jcenter.bintray.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jarnative/android/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      https://maven.google.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://maven.google.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      https://jitpack.io/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://jitpack.io/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      http://maven.microblink.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      http://maven.microblink.com/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
      https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.56.0/react-native-0.56.0.pom
      https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.56.0/react-native-0.56.0.jar
  Required by:
      project :blinkid-react-native

**Comment by i1E** [comment]
Hi @kiyokokozui,

please try the latest version of the blinkid-react-native plugin - [v4.3.0](https://github.com/BlinkID/blinkid-react-native/releases/tag/v4.3.0).

**Comment by kiyokokozui** [comment]
@i1E Thanks it works now!
