### ISSUE TITLE
UsdlCombinedRecognizer is not working for Driving license

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-react-native#86]
Hi,

I am try to scan the  Driving license of the USA and for that used the UsdlCombinedRecognizer. but I don't get any result. Whenever I Checked blinkid app from App and scan the USA driving licences it's working.

My Code : 

       var usdlRecognizer = new BlinkIDReactNative.UsdlCombinedRecognizer();
       usdlRecognizer.returnFaceImage = true;
       usdlRecognizer.returnFullDocumentImage = true;
       var usdlSuccessFrameGrabber = new BlinkIDReactNative.SuccessFrameGrabberRecognizer(usdlRecognizer);
       scanned.push(usdlSuccessFrameGrabber)(url)

And handle the result.

Please help me.

**Comment by i1E** [comment]
Hi @kiritnim,

for combined recognizers, you should use DocumentVerificationOverlaySettings instead of DocumentOverlaySettings. For example, in our sample app you should update [this line](https://github.com/BlinkID/blinkid-react-native/blob/master/demoApp/index.js#L74).

Also, you can use combined recognizers (UsdlCombinedRecognizer) directly, don't wrap it with SuccessFrameGrabberRecognizer. SuccessFrameGrabberRecognizer is used only to return the last full camera frame which arrived to the recognition.

**Comment by kiritnim** [comment]
@i1E I will try as above the front image is scanned but back image have issue. Also can't scan back image of driving license in BlinkID App.

**Comment by i1E** [comment]
Hi @kiritnim,

unfortunately, UsdlCombinedRecognizer and UsdlRecogniezr do not return the full document image, so it is not possible to obtain back side image by using these recognizers. For US driver's license, it is possible to obtain full document image of the back side only in native SDK, by using the [DetectorRecognizer](https://github.com/BlinkID/blinkid-android#-detector-recognizer).

**Comment by kiritnim** [comment]
Okay, means use of the UsdlCombinedRecognizer , the back scanning is not working,

**Comment by i1E** [comment]
Hi @kiritnim,

UsdlCombinedRecognizer scans the back side of the driver's license and extracts data from the barcode on the back side. You will get extracted data in result. As I stated earlier, `SuccessFrameGrabberRecognizer` is used to return the last full camera frame which arrived to the recognition, so if you wrap `UsdlCombinedRecognizer` with `SuccessFrameGrabberRecognizer`, you will be able to obtain full camera frame which contains back side of the document (it will not be cropped). In my first response I didn't know that back side image is important to you.

**Comment by mparadina** [comment]
Hello @kiritm-nimblechapps 

I hope we resolved your issue.

As this post is inactive, I will close it.
However, if this is still an open issue for you, please let us know.

Also, for any additional questions, you can always contact us directly at support@microblink.com.

Regards,
Milan
