### ISSUE TITLE
How to use Beta API is currently React Native?

### ISSUE THREAD

**Issue by dhrumilNimble** [BlinkID/blinkid-react-native#87]
Hi,

I checked BlinkID App and there is some Beta API, How can I used it in my apps.

**Comment by matvidako** [comment]
Hi,

we don't have a beta API, it just means that these documents aren't fully supported - we're using generic recognizers like mrtdRecognizer or documentFaceRecognizer.

If you want to know which recognizers we're using, you can check [BlinkID UI (Android)](https://github.com/BlinkID/blinkid-ui-android/blob/03105259d78fd53e829e23d0e73be0913f54728a/blinkid-ui-lib/src/main/kotlin/com/microblink/documentscanflow/country/SupportedCountry.kt).

**Comment by mparadina** [comment]
Hi @dhrumilNimble 

As this issue is inactive, I will close it.
However, if this is still an open issue for you, please let us know.

Also, you can always contact us at support@microblink.com if you encounter any obstacles.

Regards,
Milan
