### ISSUE TITLE
Update the v 4.3.0 have dependancy issue.

### ISSUE THREAD

**Issue by kiritnim** [BlinkID/blinkid-react-native#88]
Hi,

I have installed the Blinkid V 4.2.0 using the pod file, but when ever I update the pod 4.3.0 using **pod update PPBlinkID** and after run the app got the error.

Check dependencies

Argument list too long: recursive header expansion failed at ./../../node_modules/blinkid-react-native/src/ios/MicroblinkModule/../../../../../ios/Pods/React/node_modules/react-tools/src/isomorphic/children.

Thanks.

**Comment by nomi9995** [comment]
@kiritnim  how did you resolve this error
