### ISSUE TITLE
Spain National ID doesn't find in API.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-react-native#89]
HI,

I Want to scan the Spain national id card. I find api https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/spain/package-summary.html. 

But in it there is not any national card API for Spain, after I will try to use **MrtdCombinedRecognizer** for Spain scanning. 

Can you help me what I have to use for spain national ID card.

I check in iOS BlinkID app it's working for spain national id.

Thanks.

**Comment by culoi** [comment]
Hello,

This is recognizer for the Spain DL (Drivers License) not an ID. 

For the Spain ID you can use MrtdCombinedRecognizer.

Regards

**Comment by kiritnim** [comment]
Yes, I do code MrtdCombinedRecognizer

                     var spainRecognizer = new BlinkIDReactNative.MrtdCombinedRecognizer();
                     spainRecognizer.returnFaceImage = true;
                     spainRecognizer.returnFullDocumentImage = true;
                     var SuccessFrameGrabber = new BlinkIDReactNative.SuccessFrameGrabberRecognizer(spainRecognizer);
                     scanned.push(SuccessFrameGrabber)


And Scanning the image. The below image give result in BlinkId app. but according to your suggestion added code, not working at my side.

![121](https://user-images.githubusercontent.com/17870723/47420245-9edd3500-d79b-11e8-8efa-e8d5dd7a0b54.jpg)

**Comment by culoi** [comment]
Hello,

As you are using MrtdCombinedRecognizer, you should use DocumentVerificationOverlaySettings instead of DocumentOverlaySettings. Just replace this [line](https://github.com/BlinkID/blinkid-react-native/blob/master/demoApp/index.js#L74) with DocumentVerificationOverlaySettings.

Combined recognizer scan first front and then back side of the document in single camera opening.

And please remove SuccessFrameGrabberRecognizer as it is used only to return the last full camera frame.

Regards

**Comment by kiritnim** [comment]
Thanks. Working.

**Comment by kiritnim** [comment]
One more doubt, if MrtdCombinedRecognizer use this one, and after whenever I scan the france national id. The france national ID having the MRZ code at the front on the card, So whenever i scan then front part and Called results API. if I don't Scan the back part.

**Comment by matvidako** [comment]
Hi,

MrtdCombinedRecognizer expects face on the first side and MRZ on the back side so it's not usable for France.

There is currently no support for scanning both face and MRZ at the same time in our react native SDK.

If you don't require face image you can just use MrtdRecognizer.

**Comment by mparadina** [comment]
Hi @kiritm-nimblechapps 

If this is still an open issue for you, you can now scan the passport and get the face and full document image and the MRZ result with the BlinkID recognizer.

If you have any additional questions, feel free to contact us directly at support@microblink.com

Regards,
Milan

**Comment by mparadina** [comment]
Hi @kiritm-nimblechapps 

As this issue is inactive, I am closing it.
However, if this is still an open issue for you, feel free to re-open this one or create a new issue.

Also, you can always contact us directly at support@microblink.com for any additional questions.

Regards,
Milan
