### ISSUE TITLE
[iOS] Cancel button does not trigger "STATUS_SCAN_CANCELED" like on Android

### ISSUE THREAD

**Issue by Minishlink** [BlinkID/blinkid-react-native#9]
There is an inconsistency between Android and iOS. On Android, when you click on "Cancel", an error with code `STATUS_SCAN_CANCELED` is thrown, whereas on iOS there is not. (and worse, you can't know if a user has clicked on cancel in any other way)

**Comment by juraskrlec** [comment]
Hi @Minishlink 
we'll look into it and it will be fixed in new release that is coming up.

Best,
Jura

**Comment by Minishlink** [comment]
Hi @juraskrlec, do you have some info on the status of this issue?

**Comment by juraskrlec** [comment]
@Minishlink 
it will be fixed in next release that will be in 2 weeks, we'll let you know when it's released

**Comment by juraskrlec** [comment]
Hi @Minishlink 
release [v1.2.1](https://github.com/BlinkID/blinkid-react-native/releases/tag/v1.2.1) is here with a fix for this

**Comment by Minishlink** [comment]
@juraskrlec Thanks, it works well!
