### ISSUE TITLE
MrtdCombinedRecognizer display two time document front side scan overlay?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-react-native#90]
Hi,

I am using the MrtdCombinedRecognizer for the national ID Spain. it's working fine. But one problem are there. When open camera there is display document front side and after scanning it display document back side. first document scan successfully and after scan the back document. it also scan successfully. but after scan there is overly display document front side , actually I have already scan the front.

     var spainRecognizer = new BlinkIDReactNative.MrtdCombinedRecognizer();
     spainRecognizer.returnFaceImage = true;
     spainRecognizer.returnFullDocumentImage = true;
     scanned.push(spainRecognizer)

     scanningResults = await BlinkIDReactNative.BlinkID.scanWithCamera(
                         new BlinkIDReactNative.DocumentVerificationOverlaySettings(),
                         new BlinkIDReactNative.RecognizerCollection(scanned),
                         licenseKey
                     );

**Comment by i1E** [comment]
Hi @kiritnim,

can you please record a short video of this unexpected behaviour, it is not clear what exactly is happening.

**Comment by kiritnim** [comment]
Yes, I attaché video you can see after the document back scan There is display overlay with "Document front side" before push the detail page.

**VIDEO**

[Spain_Issue.zip](https://github.com/BlinkID/blinkid-react-native/files/2533586/Spain_Issue.zip)

**Comment by kiritnim** [comment]
> Hi @kiritnim,
> 
> can you please record a short video of this unexpected behaviour, it is not clear what exactly is happening.

Here is short video : https://www.dropbox.com/s/6talo32zfcdajhr/Spain_Short.mov?dl=0

**Comment by i1E** [comment]
Thank you @kiritnim, our iOS developers will check that and help you with the "Document front side" message. 

Regarding to other error that you have mentioned in the video, actually the document number is read from the back side of the document (it is inside MRZ). MrtdCombinedRecognizer just returns face image and full document image from the front side (it deos not read fields from the front side).

**Comment by kiritnim** [comment]
> Thank you @kiritnim, our iOS developers will check that and help you with the "Document front side" message.
> 
> Regarding to other error that you have mentioned in the video, actually the document number is read from the back side of the document (it is inside MRZ). MrtdCombinedRecognizer just returns face image and full document image from the front side (it deos not read fields from the front side).

Thanks.

Yes. but I have issue with message "Document front side",

**Comment by kiritnim** [comment]
> Thank you @kiritnim, our iOS developers will check that and help you with the "Document front side" message.

Do you have any update on this?

**Comment by nimblechapps** [comment]
> Thank you @kiritnim, our iOS developers will check that and help you with the "Document front side" message.

Hello, do you have any update on this issue, The issue that we are facing is after scanning the front and backside of the id, before the result screen is displayed the overlay controller flashes message to scan the front side for a fraction of time, which is confusing for the user. So we would like to seek your team's help regarding the issue.

**Comment by jcular** [comment]
Hi,

thx for reporting this, this is a bug in UI, fix is coming with the next release.

Kind regards,
Jure

**Comment by Brankacro** [comment]
Hello,
As this issue is inactive, we will close it.
In case of any questions, you can always contact us directly at support@microblink.com
Best regards,
Branka
