### ISSUE TITLE
Your license key is invalid! v 4.3

### ISSUE THREAD

**Issue by kiritnim** [BlinkID/blinkid-react-native#91]
Hi,

I am using the react-native-blinkid SDK 4.3, and creating the license form the developer account. But I have error :

Exception 'Your license key is invalid! Please 
check if you have all wanted rights' was thrown while invoking scanWithCamera 
on target blinkidIOS with params

Please help me.

**Comment by culoi** [comment]
Hello @kiritnim 

Please contact us at support@microblink.com with your bundle id and license key so we can check out where the issue is.

Best regards

**Comment by kiritnim** [comment]
Thanks I will send.
