### ISSUE TITLE
how do you auto-generate serialization wrappers?

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-react-native#94]
I saw this [commit](https://github.com/BlinkID/blinkid-react-native/commit/df8f5c056786ceb30c83707fcc8ba6739d7b01c6) and became curious :) Is it something you would be willing to share?

**Comment by DoDoENT** [comment]
What exactly would you like us to share with you?

**Comment by DoDoENT** [comment]
Hi!

We have an internal python script that uses `re` module to parse native iOS SDK headers using bunch of custom-tailored regular expressions and then use [jinja](http://jinja.pocoo.org) to generate the serialization wrappers from manually crafted templates.

The parsing script is very specific to the code style we use in our public headers and I doubt it would be very useful for general purpose and [jinja](http://jinja.pocoo.org) is open source project that we recommend for using in various use cases.

Finally, specific to react-native, we use [this python module](https://github.com/kronenthaler/mod-pbxproj) to automatically add generated files into a template xcode project that contains non-generated files (the commit you linked removed those files that were added by accident).

**Comment by mvayngrib** [comment]
@DoDoENT ah ic, thanks for explaining :)
