### ISSUE TITLE
undefined is not an object (evaluating 'BlinkIDNative.scanWithCamera')]

### ISSUE THREAD

**Issue by mkogundi** [BlinkID/blinkid-react-native#96]
[tid:com.facebook.react.JavaScript] { [TypeError: undefined is not an object (evaluating 'BlinkIDNative.scanWithCamera')]
  line: 4910,
  column: 62,
  sourceURL: '/var/containers/Bundle/Application/E23D5512-E8DC-4264-84EA-8351DD851E0A/BlinkIDReactNative.app/main.jsbundle' }

**Comment by janpieterz** [comment]
@jcular Think we're seeing something similar, works on Android but on iOS we get an undefined.
Running react-native 0.57.5, blink id react native 4.4.0 and PPBlinkId 4.4.0.
Console log similar as on Android
![image](https://user-images.githubusercontent.com/383634/49376503-c236c080-f707-11e8-8b5c-142107efecb3.png)

Probably something gone wrong with linking, doing the node_modules pod throws errors with regards to  missing properties (it relies on 4.2.0 of PPBlinkId), relying directly on PPBlinkId gives the undefined error.

Following the readme with a new project results in the same errors.

**Comment by jcular** [comment]
Hi @janpieterz,

do you have git-lfs installed.
The ios framework gets installed through cocoapods and for that you need to have git-lfs installed.
If you don't have it, you can install it though brew.
`brew install git-lfs`
`git-lfs install`
After that you'll need to clean the pod cache.
`pod cache clean --all`
and then you can run `pod install`.

This is usually the issue, let me know if this helps.

Kind regards,
Jure

**Comment by janpieterz** [comment]
Yeah, git-lfs was already installed, running again confirmed that.
`pod cache clean --all` and `pod install` didn't resolve it.

The below did, because the BlinkIDReactNative project did work I started comparing them.

Differences that resolved it were (all from within XCode):
- Libraries did not have MicroblinkModule.xcodeproj added
- Linked Frameworks and Libraries did not have libMicroblinkModule.a

**Comment by jcular** [comment]
Hi @janpieterz,

both should be added when you link blinkid-react-native.
I just tried creating na app and linking the plugin, everything worked both libMicroblinkModule and Microblinkmodule.xcodeproj were added automatically.
Here's exactly what I did:
```
react-native init MyApp
cd MyApp
npm i --save blinkid-react-native
npm install
react-native link blinkid-react-native
cd ios
pod init
``` 
changed podfile to :
```
target 'MyApp' do
  pod 'PPBlinkID', '~> 4.4.0'
end
```
`pod install`
Changed index.js.
Opened MyApp.xcworkspace;
Changed the build system to legacy(react-native doesn't seem to work well with new build system).
Run the application on device.

Do any of the steps differ from yours?

Kind regards,
Jure

**Comment by jcular** [comment]
New build system can cause some issues during building the application, but it's not the cause of the main issue here.
What bothers me is that MicroblinkModule.xcodeproj wasn't added the the project, that's the issue, but I don't understand what caused it.
Did you run `npm install`, after `npm i --save blinkid-react-native`?
I'm gonna try to recreate this, if you have any more information about what might cause this, please let me know.

Kind regards,
Jure

**Comment by janpieterz** [comment]
Yeah, for sure ran npm install (otherwise manual linking wouldn't work either).
The only thing I could think of was that it might have been done first on a Windows machine for Android only, and _then_ on a mac to bring ios in. But the steps (install, link, pod install were run on both)

**Comment by kakakalot** [comment]
@jcular 
I also meet this issue with pod install. I think pod lib BlinkID v4.4.0 has problem because I cannot see `MBMicroblinkModule` header file in the `<RNBlinkApp>/ios/Pods/PPBlinkID/MicroBlink.framework/Headers/` folder.

**Comment by mkogundi** [comment]
Hi @janpieterz  @jcular 

i have tried all the above approaches i have the scan button but when i click on that its throwing this error 

BlinkIDReactNativeApp[521:117841] { [TypeError: undefined is not an object (evaluating 'BlinkIDNative.scanWithCamera')]
  line: 83001,
  column: 64,
  sourceURL: '/var/containers/Bundle/Application/E82096D0-F97D-45C4-AE90-19F0F3C0F954/BlinkIDReactNativeApp.app/main.jsbundle' }

i need this to be resolved asap any support would be helpful 

its causing this error only in IOS

**Comment by jcular** [comment]
Hi @mkogundi,

What version of RN are you using, also what version of our SDK?

@kakakalot MBMicroblinkModule shouldn't be a part of PPBlinkID pod so that's not the cause of this issue.

Kind regards,
Jure

**Comment by mkogundi** [comment]
Hi @jcular 

Below is the Package.json 

{
  "name": "BlinkIDReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "blinkid-react-native": "^4.4.0",
    "react": "16.6.3",
    "react-native": "0.57.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.5",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

i have followed these steps 

react-native init MyApp
cd MyApp
npm i --save blinkid-react-native
npm install
react-native link blinkid-react-native
cd ios
pod init
changed podfile to :

target 'MyApp' do
  pod 'PPBlinkID', '~> 4.4.0'
end
pod install
Changed index.js.
Opened MyApp.xcworkspace;

Xcode : Version 9.4.1

i dont have the option to change the build system to legacy 
Hoping to hear something from you 

i have also tried your demo project with 0.56 version and PPBlink 4.4.2 but it just doesn't build 
i was able to build and run the app on Android but IOS just doesn't seem to work 
Let me know if you have any suggestions 

Regards
Manish

**Comment by jcular** [comment]
Hi @mkogundi,

usually, this happens because of missing `git-lfs`. Do you have it installed? If you do have you tried [this.](https://github.com/BlinkID/blinkid-react-native/issues/96#issuecomment-444000331)
Have you tried installing an older version of BlinkID-react-native?
Can you send us the output when you run `initReactNativeDemo.sh`?

Kind regards,
Jure

**Comment by mparadina** [comment]
Hi, 

As this issue is inactive we would like to solve it. 

In case of any questions, feel free to re-open this issue or create a new one.
Also, you can contact us directly at support@microblink.com for additional questions.
We will be more than glad to help.

Regards,
Milan
