### ISSUE TITLE
Is it possible to read both sides of idcard and combine their raw images?

### ISSUE THREAD

**Issue by Hongdeshuai** [BlinkID/blinkid-react-native#98]

**Comment by XiaoXing44** [comment]
Yes, CombinedRecognizer will be helpful. But customization of overlay is not possible
Thank you

**Comment by jcular** [comment]
Hi @Hongdeshuai,

as @XiaoXing44 said you can get both side images using combined recognizers, but the images are separated. You can combine the images once you get them from valid results.

Kind regards,
Jure

**Comment by Hongdeshuai** [comment]
Thank you.
I can now read both sides using combined recognizer.
By the way, have you any idea if we can not success reading back side, to get back with the result of front side ?
Actually, even we success for front side, if we fail for the back side, then we can only get back to our app without any result, losing the result of the front side too . .

**Comment by XiaoXing44** [comment]
Is it possible to get full document image if scanning is failed because of some reason?
And I wanna make an alert if scanning is failed in certain time like 10 seconds.
So scanning is not successful in 10 seconds, users can see alert
In react native

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jcular** [comment]
@Hongdeshuai this could be done on native using separated recognizer for front and back side.
The current implementation of rn plugin returns as soon as one recognizer becomes valid, so using two recognizers in one scanning session is impossible.

@XiaoXing44 no you can't get the document image if scanning is unsuccessful.
As for the alert, I'm not sure if it's possible. I think you can do it by setting a timer before starting the scan then once the scanning is started you can start the timer and if the 10 seconds pass the timer creates an alert. If the scanning is canceled or successful stop the timer.

**Comment by Hongdeshuai** [comment]
Thank you very much for your kind reply.

**Comment by mparadina** [comment]
Hi,

As this issue is inactive we would like to solve it. 
In case of any questions, feel free to re-open the issue or create a new one.

Also, you can always contact us directly at support@microblink.com for further questions.
We will be more than glad to help.

Regards,
Milan
